### ISSUE TITLE
handleWindowResize setInterval spam

### ISSUE THREAD

**Issue by scriby** [tinymce/tinymce-dist#17]
I was doing some profiling of our app at work today and noticed a lot of noise in the timeline view: http://screencast.com/t/UP3g6YKPEbAI. That timeline was taken while the app is not being used.

I was curious what was causing all that, so I tracked down the source, which turned out to be a setInterval in tinyMCE:

```
Delay.setInterval(function() {
  var w = window.innerWidth,
    h = window.innerHeight;

  if (lastSize.w != w || lastSize.h != h) {
    lastSize = {
      w: w,
      h: h
    };

    $(window).trigger('resize');
  }
});
```

The first thing to notice is that this setInterval runs with a delay of 0. I am not sure if this is a necessity, but something like this would typically be delayed around 100+ ms to not contend for resources.

The next thing to notice is that this code shouldn't even be kicking in:

```
if (!Env.desktop) {
  handleWindowResize();
}
```

I am most certainly using a desktop, so what is going on? I checked the code for Env, and I don't see that it has any code to set the desktop property. So, it's always going to be falsey and run the resize handler code.

Thanks,

Chris

**Comment by spocke** [comment]
Please use the other issue tracker. I guess we should remove this issue tracker since it's confusing to have two of them. I fixed these issues though.
