### ISSUE TITLE
Include languages in tinymce-dist

### ISSUE THREAD

**Issue by thet** [tinymce/tinymce-dist#4]
`tinymce-dist` isn't complete with all languages bundled with it. `tinymce-builded` provides them: https://github.com/artursmirnov/tinymce_builded/tree/master/js/tinymce/langs

**Comment by softwaymedical** [comment]
Could you please update [tinymce-builded](https://github.com/artursmirnov/tinymce_builded) to v4.1.7 in order that we use it.

Hopefully that [tinymce-dist](https://github.com/tinymce/tinymce-dist) will bundle a new version with all languages.

**Comment by thet** [comment]
duplicate of https://github.com/tinymce/tinymce-dist/issues/8

**Comment by Rvanlaak** [comment]
:+1:
